# Generated by Django 3.2.9 on 2021-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['identifier', 'secret'], name='client_clie_identif_cb0351_idx'),
        ),
    ]
