# Generated by Django 3.2.9 on 2021-11-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('crawler', models.CharField(db_index=True, max_length=255)),
                ('crawler_config', models.JSONField(blank=True, null=True)),
                ('run_after_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(db_index=True, max_length=255)),
                ('is_enabled', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('item_uid', models.CharField(max_length=255, unique=True)),
                ('item', models.JSONField()),
                ('status', models.CharField(max_length=255)),
                ('status_reason', models.TextField(blank=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawler.crawler')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
